"""
Supply Chain SNA — Decentralized Transaction Layer
PHASE 19: Abstraction layer for transaction storage and retrieval.

Implements:
  - TransactionStore: Abstract base class (interface)
  - SyntheticTransactionStore: Uses generated CSV data (primary)
  - BlockchainTransactionStore: Placeholder for future real blockchain integration

The SNA engine is completely decoupled from this layer.
It only requires a DataFrame of transactions — it does not care where they came from.
"""
from __future__ import annotations

import hashlib
import json
import logging
from abc import ABC, abstractmethod
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd

logger = logging.getLogger(__name__)


class TransactionStore(ABC):
    """Abstract base class for transaction storage backends.

    Defines the interface that any transaction backend must implement.
    The SNA engine uses only read_transactions() to get data for graph construction.
    """

    @abstractmethod
    def write_transaction(self, transaction: dict[str, Any]) -> str:
        """Write a single transaction to the store.

        Args:
            transaction: Transaction dictionary matching the required schema.

        Returns:
            Transaction ID assigned by the store.
        """

    @abstractmethod
    def read_transactions(
        self,
        start_date: str | None = None,
        end_date: str | None = None,
        source_node: str | None = None,
        target_node: str | None = None,
    ) -> pd.DataFrame:
        """Read transactions from the store with optional filters.

        Args:
            start_date: ISO date string filter (inclusive).
            end_date: ISO date string filter (inclusive).
            source_node: Filter by source organization ID.
            target_node: Filter by target organization ID.

        Returns:
            DataFrame of matching transactions.
        """

    @abstractmethod
    def verify_transaction(self, transaction_id: str) -> dict[str, Any]:
        """Verify the integrity of a transaction record.

        Args:
            transaction_id: Transaction ID to verify.

        Returns:
            Dictionary with keys: is_valid, transaction_id, hash, message.
        """


class SyntheticTransactionStore(TransactionStore):
    """Transaction store backed by the synthetic CSV dataset.

    This is the primary implementation used by the SNA pipeline.
    It loads from CSV files generated by the data generator.
    """

    def __init__(self, data_dir: str | Path) -> None:
        """Initialize the store.

        Args:
            data_dir: Directory containing organizations.csv and transactions.csv.
        """
        self.data_dir = Path(data_dir)
        self._transactions: pd.DataFrame | None = None
        self._hashes: dict[str, str] = {}

    def _load(self) -> pd.DataFrame:
        """Load transactions from CSV if not already loaded.

        Returns:
            Transactions DataFrame.
        """
        if self._transactions is None:
            path = self.data_dir / "transactions.csv"
            if not path.exists():
                raise FileNotFoundError(f"Transactions CSV not found: {path}")
            self._transactions = pd.read_csv(path)
            # Compute hashes for integrity verification
            for _, row in self._transactions.iterrows():
                row_json = json.dumps(row.to_dict(), sort_keys=True, default=str)
                self._hashes[row["transaction_id"]] = hashlib.sha256(
                    row_json.encode()
                ).hexdigest()
            logger.info("Loaded %d transactions from %s", len(self._transactions), path)
        return self._transactions

    def write_transaction(self, transaction: dict[str, Any]) -> str:
        """Append a transaction to the in-memory store.

        Note: Does not persist to CSV (synthetic store is read-only by default).
        Use for testing only.

        Args:
            transaction: Transaction dictionary.

        Returns:
            Transaction ID.
        """
        df = self._load()
        txn_id = transaction.get("transaction_id", f"TXN-MANUAL-{len(df)+1:06d}")
        transaction["transaction_id"] = txn_id
        row_json = json.dumps(transaction, sort_keys=True, default=str)
        self._hashes[txn_id] = hashlib.sha256(row_json.encode()).hexdigest()
        new_row = pd.DataFrame([transaction])
        self._transactions = pd.concat([df, new_row], ignore_index=True)
        logger.info("Written transaction %s to in-memory store", txn_id)
        return txn_id

    def read_transactions(
        self,
        start_date: str | None = None,
        end_date: str | None = None,
        source_node: str | None = None,
        target_node: str | None = None,
    ) -> pd.DataFrame:
        """Read transactions with optional filters.

        Args:
            start_date: ISO date filter.
            end_date: ISO date filter.
            source_node: Source org ID filter.
            target_node: Target org ID filter.

        Returns:
            Filtered DataFrame.
        """
        df = self._load().copy()

        if start_date and "timestamp" in df.columns:
            df = df[df["timestamp"] >= start_date]
        if end_date and "timestamp" in df.columns:
            df = df[df["timestamp"] <= end_date]
        if source_node:
            df = df[df["source_node"] == source_node]
        if target_node:
            df = df[df["target_node"] == target_node]

        return df.reset_index(drop=True)

    def verify_transaction(self, transaction_id: str) -> dict[str, Any]:
        """Verify transaction integrity via stored hash.

        Args:
            transaction_id: Transaction ID to verify.

        Returns:
            Verification result dictionary.
        """
        df = self._load()
        row = df[df["transaction_id"] == transaction_id]

        if row.empty:
            return {
                "is_valid": False,
                "transaction_id": transaction_id,
                "hash": None,
                "message": "Transaction not found",
            }

        row_json = json.dumps(row.iloc[0].to_dict(), sort_keys=True, default=str)
        current_hash = hashlib.sha256(row_json.encode()).hexdigest()
        stored_hash = self._hashes.get(transaction_id)

        # For synthetic data, hashes match by construction
        is_valid = stored_hash is None or current_hash == stored_hash
        return {
            "is_valid": is_valid,
            "transaction_id": transaction_id,
            "hash": current_hash,
            "message": "Hash verified" if is_valid else "Hash mismatch — possible tampering",
        }


class BlockchainTransactionStore(TransactionStore):
    """Placeholder for a real blockchain-backed transaction store.

    This class documents the integration point for a real blockchain
    (e.g., Hyperledger Fabric or a permissioned Ethereum network).

    Architecture:
        Transaction
            ↓
        Validation
            ↓
        Ledger (blockchain)
            ↓
        Retrieval
            ↓
        Graph Builder

    The SNA engine does not need to be modified to switch backends.
    Only this class needs to be implemented with real blockchain calls.
    """

    def __init__(self, endpoint: str = "http://localhost:8080") -> None:
        """Initialize the blockchain store (not implemented).

        Args:
            endpoint: Blockchain node endpoint URL.
        """
        self.endpoint = endpoint
        logger.warning(
            "BlockchainTransactionStore is a placeholder. "
            "Real blockchain integration is not implemented. "
            "Use SyntheticTransactionStore for production use of this academic prototype."
        )

    def write_transaction(self, transaction: dict[str, Any]) -> str:
        raise NotImplementedError(
            "Real blockchain integration not implemented. "
            "This is an integration point for Hyperledger Fabric or similar."
        )

    def read_transactions(self, **kwargs) -> pd.DataFrame:
        raise NotImplementedError(
            "Real blockchain integration not implemented."
        )

    def verify_transaction(self, transaction_id: str) -> dict[str, Any]:
        raise NotImplementedError(
            "Real blockchain integration not implemented."
        )
